name: poke_radar
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.4.4

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  intl: ^0.19.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/animations/
    - assets/images/
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/core/config/intl
  output_dir: lib/core/config/intl
